#!/bin/bash

NAME="sroaddiction"                                 # Name of the application
DJANGODIR=/var/www/sroaddiction/                    # Django project directory
SOCKFILE=/var/www/sroaddiction/run/gunicorn.sock    # we will communicte using this unix socket
USER=root                                           # the user to run as
GROUP=root                                          # the group to run as
NUM_WORKERS=3                                       # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=sroaddiction.settings        # which settings file should Django use
DJANGO_WSGI_MODULE=sroaddiction.wsgi                # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
. /root/.virtualenvs/sroaddiction/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /root/.virtualenvs/sroaddiction/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE